name: Chemprompt
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - rdkit=2023.09.6
  - pip
  - pip:
      - deepchem==2.8.0
      - sentence-transformers==3.3.1
      - sentencepiece==0.2.0
      - pytdc==1.1.15
      # - transformers==4.56.2
